///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace VersionTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Moduel4 recording.
    /// </summary>
    [TestModule("8eaad0d8-12eb-407a-ba8f-c4b475c9f05e", ModuleType.Recording, 1)]
    public partial class Moduel4 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the VersionTestRepository repository.
        /// </summary>
        public static VersionTestRepository repo = VersionTestRepository.Instance;

        static Moduel4 instance = new Moduel4();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Moduel4()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Moduel4 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'http://testgames.be/connections/' with browser 'chrome' in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("http://testgames.be/connections/", "chrome", "", false, false, false, false, false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ConnectionManager.Logout' at 62;68.", repo.ConnectionManager.LogoutInfo, new RecordItemIndex(1));
            repo.ConnectionManager.Logout.Click("62;68");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ConnectionManager.Username' at 17;15.", repo.ConnectionManager.UsernameInfo, new RecordItemIndex(2));
            repo.ConnectionManager.Username.Click("17;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'admin' with focus on 'ConnectionManager.Username'.", repo.ConnectionManager.UsernameInfo, new RecordItemIndex(3));
            repo.ConnectionManager.Username.PressKeys("admin");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ConnectionManager.Password' at 17;10.", repo.ConnectionManager.PasswordInfo, new RecordItemIndex(4));
            repo.ConnectionManager.Password.Click("17;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'superduper' with focus on 'ConnectionManager.Password'.", repo.ConnectionManager.PasswordInfo, new RecordItemIndex(5));
            repo.ConnectionManager.Password.PressKeys("superduper");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ConnectionManager.LogIn' at 9;5.", repo.ConnectionManager.LogInInfo, new RecordItemIndex(6));
            repo.ConnectionManager.LogIn.Click("9;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ConnectionManager.Stats' at 38;64.", repo.ConnectionManager.StatsInfo, new RecordItemIndex(7));
            repo.ConnectionManager.Stats.Click("38;64");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
