///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace VersionTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the VersionTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
    [RepositoryFolder("4461e78c-0770-4a91-99fb-558c3ec87e6e")]
    public partial class VersionTestRepository : RepoGenBaseFolder
    {
        static VersionTestRepository instance = new VersionTestRepository();
        VersionTestRepositoryFolders.ConnectionManagerAppFolder _connectionmanager;

        /// <summary>
        /// Gets the singleton class instance representing the VersionTestRepository element repository.
        /// </summary>
        [RepositoryFolder("4461e78c-0770-4a91-99fb-558c3ec87e6e")]
        public static VersionTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public VersionTestRepository() 
            : base("VersionTestRepository", "/", null, 0, false, "4461e78c-0770-4a91-99fb-558c3ec87e6e", ".\\RepositoryImages\\VersionTestRepository4461e78c.rximgres")
        {
            _connectionmanager = new VersionTestRepositoryFolders.ConnectionManagerAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("4461e78c-0770-4a91-99fb-558c3ec87e6e")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ConnectionManager folder.
        /// </summary>
        [RepositoryFolder("152c635c-3b48-42d8-809c-738d5b92d20b")]
        public virtual VersionTestRepositoryFolders.ConnectionManagerAppFolder ConnectionManager
        {
            get { return _connectionmanager; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
    public partial class VersionTestRepositoryFolders
    {
        /// <summary>
        /// The ConnectionManagerAppFolder folder.
        /// </summary>
        [RepositoryFolder("152c635c-3b48-42d8-809c-738d5b92d20b")]
        public partial class ConnectionManagerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _logoutInfo;
            RepoItemInfo _usernameInfo;
            RepoItemInfo _passwordInfo;
            RepoItemInfo _contentInfo;
            RepoItemInfo _languageInfo;
            RepoItemInfo _buttonInfo;

            /// <summary>
            /// Creates a new ConnectionManager  folder.
            /// </summary>
            public ConnectionManagerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ConnectionManager", "/dom[@domain='testgames.be']", parentFolder, 30000, null, false, "152c635c-3b48-42d8-809c-738d5b92d20b", "")
            {
                _logoutInfo = new RepoItemInfo(this, "Logout", ".//a[#'logout']", 30000, null, "9c20ab7a-b8db-443e-b51f-8037bbdfdf81");
                _usernameInfo = new RepoItemInfo(this, "Username", ".//input[#'username']", 30000, null, "af855205-844d-4fdc-b5c2-3937b53be850");
                _passwordInfo = new RepoItemInfo(this, "Password", ".//input[#'password']", 30000, null, "ec8a5efc-a715-4926-9f99-d8030d4ae773");
                _contentInfo = new RepoItemInfo(this, "Content", ".//div[#'login']/table//span", 30000, null, "c952dd20-4e20-41d8-b6a4-840994ab34e0");
                _languageInfo = new RepoItemInfo(this, "Language", ".//div[#'login']/select[@name='language']", 30000, null, "e0f4f51a-51d3-4e1c-a3c2-d4e7fcd8ca86");
                _buttonInfo = new RepoItemInfo(this, "Button", ".//div[#'welcome']/?/?/input[@type='button']", 30000, null, "a1ecf1fd-c420-4c64-9099-91a5ddad9eca");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("152c635c-3b48-42d8-809c-738d5b92d20b")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("152c635c-3b48-42d8-809c-738d5b92d20b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Logout item.
            /// </summary>
            [RepositoryItem("9c20ab7a-b8db-443e-b51f-8037bbdfdf81")]
            public virtual Ranorex.ATag Logout
            {
                get
                {
                    return _logoutInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Logout item info.
            /// </summary>
            [RepositoryItemInfo("9c20ab7a-b8db-443e-b51f-8037bbdfdf81")]
            public virtual RepoItemInfo LogoutInfo
            {
                get
                {
                    return _logoutInfo;
                }
            }

            /// <summary>
            /// The Username item.
            /// </summary>
            [RepositoryItem("af855205-844d-4fdc-b5c2-3937b53be850")]
            public virtual Ranorex.InputTag Username
            {
                get
                {
                    return _usernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Username item info.
            /// </summary>
            [RepositoryItemInfo("af855205-844d-4fdc-b5c2-3937b53be850")]
            public virtual RepoItemInfo UsernameInfo
            {
                get
                {
                    return _usernameInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("ec8a5efc-a715-4926-9f99-d8030d4ae773")]
            public virtual Ranorex.InputTag Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("ec8a5efc-a715-4926-9f99-d8030d4ae773")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The Content item.
            /// </summary>
            [RepositoryItem("c952dd20-4e20-41d8-b6a4-840994ab34e0")]
            public virtual Ranorex.SpanTag Content
            {
                get
                {
                    return _contentInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Content item info.
            /// </summary>
            [RepositoryItemInfo("c952dd20-4e20-41d8-b6a4-840994ab34e0")]
            public virtual RepoItemInfo ContentInfo
            {
                get
                {
                    return _contentInfo;
                }
            }

            /// <summary>
            /// The Language item.
            /// </summary>
            [RepositoryItem("e0f4f51a-51d3-4e1c-a3c2-d4e7fcd8ca86")]
            public virtual Ranorex.SelectTag Language
            {
                get
                {
                    return _languageInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The Language item info.
            /// </summary>
            [RepositoryItemInfo("e0f4f51a-51d3-4e1c-a3c2-d4e7fcd8ca86")]
            public virtual RepoItemInfo LanguageInfo
            {
                get
                {
                    return _languageInfo;
                }
            }

            /// <summary>
            /// The Button item.
            /// </summary>
            [RepositoryItem("a1ecf1fd-c420-4c64-9099-91a5ddad9eca")]
            public virtual Ranorex.InputTag Button
            {
                get
                {
                    return _buttonInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Button item info.
            /// </summary>
            [RepositoryItemInfo("a1ecf1fd-c420-4c64-9099-91a5ddad9eca")]
            public virtual RepoItemInfo ButtonInfo
            {
                get
                {
                    return _buttonInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}